print('Welcome to Mad Lib! Please type the correct figure of speech.')
#Append to list 'words'
wordlist = [0]
#ask for each part of speech
name1 = input('Name:')
wordlist.append(name1)
verb1 = input('Verb:')
wordlist.append(verb1)
adjective1 = input('Adjective:')
wordlist.append(adjective1)
adjective2 = input('Adjective:')
wordlist.append(adjective2)
noun1 = input('Noun:')
wordlist.append(noun1)
number1 = int(input('Number:'))
wordlist.append(number1)
adjective3 = input('Adjective:')
wordlist.append(adjective3)
adjective4 = input('Adjective:')
wordlist.append(adjective4)
number2 = int(input('Number:'))
wordlist.append(number2)
exclamatory = input('Interjection:')
wordlist.append(exclamatory)
noun2 = input('Noun:')
wordlist.append(noun2)
adjective5 = input('Adjective:')
wordlist.append(adjective5)
pnoun1 = input('Noun(plural):')
wordlist.append(pnoun1)
pnoun2 = input('Noun(plural):')
wordlist.append(pnoun2)
pnoun3 = input('Noun(plural):')
wordlist.append(pnoun3)
noun3 = input('Noun:')
wordlist.append(noun3)
verb2 = input('Verb:')
wordlist.append(verb2)
adverb = input('Adverb:')
wordlist.append(adverb)
adjective6 = input('Adjective:')
wordlist.append(adjective6)
#put in for each space
print('\n\nHiking With',wordlist[1])
print('Hi, my name is ',wordlist[1],'. One of my hobbies is to',wordlist[2],'in the mountains.\n I cannot get enough of the ',wordlist[3],' and ',wordlist[4],' mountain ',wordlist[5],'. I probably go hiking ',wordlist[6],' times a week!\n *   .    *     .           Yesterday, I traveled far to hike a ',wordlist[7],'and ',wordlist[8],'\n      .  ,--.  *            mountain. It was about ',wordlist[9],' hours long!\n  .     /----\   /\        ',wordlist[10],'! That’s the longest ',wordlist[11],'\n   *   /^   ^ \ /--\        I have ever heard of! It was ',wordlist[12],'. I could \n      /  /\ ^  /^ ^ \      see so many species of ',wordlist[13],'\n  .  /^ /--\  / ^  ^ \      and ',wordlist[14],' and ',wordlist[15],' that \n    / ^/  ^ \/ __^  ^ \    I could identify with my',wordlist[16],'. \n   /  / ^ ^  \/^^\/\ ^ \   As I get better at ',wordlist[17],', it becomes \n__/__/_______/___/__\___\__',wordlist[18],' more ',wordlist[19],'!')